apiVersion: v1
kind: Service
metadata:
  name: dispatch
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: dispatch
status:
  loadBalancer: {}
