apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
  - protocol: TCP
    port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq