apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels: 
        app: web
    spec:
      containers:
        - name:  web
          image:  linuxacademycontent/rs-web:latest
          imagePullPolicy: Always
          ports:
          - containerPort:  8080
          readinessProbe:
             httpGet:
               path: /
               port: 8080
               initialDelaySeconds: 5
               periodSeconds: 5
               successThreshold: 1 
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
